language: r
sudo : false
cache: packages

install:
  - sudo apt-get install -y gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

r:
  - release

r_packages:
  - Rcpp
  - RcppArmadillo
  - methods

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::coveralls()'
