language: r
sudo : false
cache: packages

r:
  - release

r_packages:
  - Rcpp
  - RcppArmadillo
  - methods

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::coveralls()'

before_deploy:
  - Rscript -e 'devtools::install(quick = TRUE); install.packages("mlbench"); devtools::document(); pkgdown::build_site();'
  # - Rscript -e 'devtools::install(quick = TRUE); devtools::document(); devtools::build_vignettes(); pkgdown::build_site();'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  local-dir: docs
  on:
    branch: master