language: r
sudo : false
cache: packages

r:
  - release

r_packages:
  - Rcpp
  - RcppArmadillo
  - methods

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::coveralls()'

before_deploy:
  - Rscript -e 'devtools::install(quick = TRUE); install.packages(c("mlbench", "ggthemes", "gridExtra")); devtools::document(); pkgdown::build_site();'
  # - Rscript -e 'devtools::install(quick = TRUE); devtools::document(); devtools::build_vignettes(); pkgdown::build_site();'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  local-dir: docs
  on:
    branch: master

after_deploy:
  - git checkout master
  - Rscript -e 'rmarkdown::render("Readme.Rmd")'
  - git add Readme.md
  - git add Readme_files
  - git commit -m "travis - update Readme"
  - git push origin master